### ISSUE TITLE
How to install this driver?

### ISSUE THREAD

**Issue by ankush981** [joedixon/botman-driver-ubisend#1]
Hello, I'm reading the ebook by Joe Dixon, and while it goes into a lot of detail about how to create a custom driver, it doesn't tell how to install this driver. Do I simply drop the code inside the `src` directory? Some help will be appreciated!

**Comment by joedixon** [comment]
Hi,

You can install via composer by adding `"joedixon/botman-driver-ubisend": "dev-master",` to the require section of your composer.json file and then running `composer update` on the command line.

You can see the full source code for the bot [here](https://github.com/joedixon/bot) to see how it is utilised. Please let me know if you have any questions.

**Comment by ankush981** [comment]
Thank you so much! May I request that these instructions be added to the book? The book doesn't mention the composer package (at least I couldn't find it), and when I did discover the package, I was running around in circles dealing with `minimum-stability` issues. :-\

**Comment by joedixon** [comment]
Really appreciate that feedback. This will definitely get highlighted in any future iterations of the book.
